name: wiseworkout
description: "A new Flutter project for personal workout."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.7.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Package metier - Pour empecher la mise en veille de l'app
  wakelock_plus: ^1.3.2

  # Logo and splash_master
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

  # Audio
  audioplayers: ^6.0.0

  # Cache
  shared_preferences: ^2.5.3

  # Version info
  package_info_plus: ^10.1.0

  # Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Data Provider
  signals: ^7.1.0
  signals_flutter: ^7.1.0
  signals_core: ^7.0.0

  # Date
  intl: ^0.20.2

  # Graph
  fl_chart: ^1.2.0

  # File
  path: ^1.9.1
  path_provider: ^2.1.5

  # Database
  get_it: ^9.0.5
  sqlite3_flutter_libs: ^0.5.22
  drift: ^2.29.0

  # Toast
  fluttertoast: ^9.0.0

  # internationalization
  flutter_localizations:
    sdk: flutter

  # Markdown
  flutter_markdown: ^0.7.7+1

  # Webview
  webview_flutter: ^4.7.0

  # Flags
  country_flags: ^4.1.0

  # Firebase
  firebase_core: ^4.3.0

  # Env
  flutter_dotenv: ^6.0.0

  # Feedback
  feedback: ^3.2.0
  http: ^1.6.0
  device_info_plus: ^13.1.0
  upgrader: ^13.4.0

  # Networking & Functional Programming (from core packages)
  dio: ^5.7.0
  dartz: ^0.10.1
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Builder
  build_runner: ^2.5.4

  # Linter
  very_good_analysis: ^10.1.0

  # Models dev
  freezed: ^3.2.3
  json_serializable: ^6.9.4

  # Database dev
  drift_dev: ^2.29.0

  # Mocking
  mockito: ^5.4.4

dependency_overrides:
  path_provider_android: 2.2.22
  drift: 2.29.0
  drift_dev: 2.29.0
  sqlite3: 2.9.4
  sqlite3_flutter_libs: 0.5.42

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/markdown/
    - assets/common/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-VariableFont_wdth,wght.ttf
        - asset: fonts/roboto/Roboto_Condensed-SemiBold.ttf
          weight: 700
