name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env from example
        run: cp .env.example .env

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web (WASM)
        run: flutter build web --wasm --base-href /wiseworkout/

      # Étape de secours pour les serveurs comme GitHub Pages qui gèrent mal le WASM pur
      - name: Ensure correct routing for GitHub Pages
        run: |
          cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.SECRET_FOR_DEPLOY_WISEWORKOUT }}
          branch: gh-pages
          folder: build/web
          clean: true # Force le nettoyage pour éviter les conflits de fichiers